-- MySQL Script generated by MySQL Workbench
-- Tue Aug 17 22:25:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema japanbites
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema japanbites
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `japanbites` DEFAULT CHARACTER SET utf8 ;
USE `japanbites` ;

-- -----------------------------------------------------
-- Table `japanbites`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `japanbites`.`users` (
  `id` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `japanbites`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `japanbites`.`dishes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `japanbites`.`users_dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `japanbites`.`users_dishes` (
  `users_id` INT NOT NULL,
  `dishes_id` INT NOT NULL,
  `dt` DATETIME NOT NULL,
  `mark` INT NULL,
  PRIMARY KEY (`users_id`, `dishes_id`),
  INDEX `fk_users_has_dishes_dishes1_idx` (`dishes_id` ASC) VISIBLE,
  INDEX `fk_users_has_dishes_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_dishes_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `japanbites`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_dishes_dishes1`
    FOREIGN KEY (`dishes_id`)
    REFERENCES `japanbites`.`dishes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
